#### IoT사물인터넷 with 라즈베리파이 평가대비문제

In [23]:
# 코드 작성 전 이 셀을 실행하여 pandas 라이브러리를 import 하세요.
import pandas as pd
df = pd.read_excel('order.xlsx') 
df

      주문번호  고객명  카테고리  지역      판매금액   수량   할인율   평점
0   ORD001  김민준  전자제품  서울  120000.0  2.0  10.0  4.5
1   ORD002  이서연    의류  부산   45000.0  3.0   0.0  3.8
2   ORD003  박지호  전자제품  서울  230000.0  1.0  15.0  NaN
3   ORD004  최수아    식품  대구   18000.0  5.0   0.0  4.2
4   ORD005  정우진    의류  서울   67000.0  4.0   5.0  4.0
5   ORD006  강하은  전자제품  부산  310000.0  1.0  20.0  NaN
6   ORD007  윤도현    식품  대구   22000.0  6.0   0.0  3.5
7   ORD008  임지유   NaN  서울   89000.0  2.0  10.0  4.7
8   ORD009  한준서    의류  부산   54000.0  3.0   5.0  3.9
9   ORD010  오서현  전자제품  대구  175000.0  1.0  15.0  4.3
10  ORD011  배준혁    식품  서울   31000.0  4.0   0.0  4.1
11  ORD012  신하은    의류  부산   48000.0  2.0   NaN  3.7
12  ORD013  류지원   NaN  서울   95000.0  3.0  10.0  NaN
13  ORD014  문서준  전자제품  대구       NaN  NaN  20.0  4.8
14  ORD015  남다인    식품  부산   27000.0  5.0   0.0  4.0

문제 1. 공유폴더에 제공한 'order.xlsx' 파일을 불러와 DataFrame 데이터를 'df'로 생성

In [ ]:
#문제 1번 풀이 작성

문제 2. 컬럼별 결측치의 갯수를 파악하여 결측치의 갯수가 가장 많은 컬럼명을 변수 '답_02'에 저장하세요.  
ex> 답_02 = '컬럼1'  
ex> 답_02 = '컬럼1, 컬럼2'

In [13]:
#문제 2번 풀이 작성
print(df.isnull().sum())
답_02 = '평점'
답_02

주문번호    0
고객명     0
카테고리    2
지역      0
판매금액    1
수량      1
할인율     1
평점      3
dtype: int64

'평점'

문제 3. df 데이터를 아래 기준으로 결측치를 처리하세요. 처리된 결과는 df에 저장되어야 합니다.  
1) 카테고리 컬럼 -> '미분류'로 채우기  
2) 한인율 -> 0으로 채우기  
3) 판매금액 -> 평균값으로 채우기  
4) 수량 -> 중앙값으로 채우기
5) 평점 -> 평균값으로 채우기(소수점 둘째 자리)

In [ ]:
#문제 3번 풀이 작성
# 1) 카테고리 -> '미분류'로 채우기
df['카테고리'] = df['카테고리'].fillna('미분류')

# 2) 할인율 -> 0으로 채우기
df['할인율'] = df['할인율'].fillna(0)

# 3) 판매금액 -> 평균값으로 채우기
df['판매금액'] = df['판매금액'].fillna(df['판매금액'].mean())

# 4) 수량 -> 중앙값으로 채우기
df['수량'] = df['수량'].fillna(df['수량'].median())

# 5) 평점 -> 평균값으로 채우기 (소수점 둘째 자리)
df['평점'] = df['평점'].fillna(round(df['평점'].mean(), 2))

df

문제 4. df에서 '카테고리'와 '지역' 컬럼만 선택하여 출력하세요.

In [ ]:
#문제 4번 풀이 작성
df[['카테고리','지역']]

문제 5. df에서 지역이 '서울'이거나 '부산'인 주문 중 평점이 4.0 이상이 주문 정보를 출력하세요.

In [18]:
#문제 5번 풀이 작성
df[(  (df['지역'] == '서울') | (df['지역'] == '부산')  ) & (df['평점'] >= 4.0)]

      주문번호  고객명  카테고리  지역      판매금액   수량   할인율   평점
0   ORD001  김민준  전자제품  서울  120000.0  2.0  10.0  4.5
4   ORD005  정우진    의류  서울   67000.0  4.0   5.0  4.0
7   ORD008  임지유   NaN  서울   89000.0  2.0  10.0  4.7
10  ORD011  배준혁    식품  서울   31000.0  4.0   0.0  4.1
14  ORD015  남다인    식품  부산   27000.0  5.0   0.0  4.0

문제 6. df 데이터를 아래 요구사항에 맞게 데이터를 변경하세요.  
1) '판매금액'과 '수량'을 곱한 '총판매액' 컬럼을 추가하세요
2) '지역'컬럼에서 '대구'를 '대구광역시'로 변경하세요.

In [ ]:
#문제 6번 풀이 작성
df['지역'] = df['지역'].replace('대구','대구광역시')
df

문제 7. df 데이터에서 카테고리별 판매금액의 합계를 출력하시오.

In [27]:
#문제 7번 풀이 작성
df.groupby('카테고리')['판매금액'].sum()

카테고리
식품       98000.0
의류      214000.0
전자제품    835000.0
Name: 판매금액, dtype: float64

문제 8. 판매금액 기준 내림차순으로 정렬하고, 상위 5개 주문의 고객명과 판매금액을 출력하세요.

In [28]:
#문제 8번 풀이 작성
df.sort_values('판매금액',ascending=False)[['고객명','판매금액']].head(5)

    고객명      판매금액
5   강하은  310000.0
2   박지호  230000.0
9   오서현  175000.0
0   김민준  120000.0
12  류지원   95000.0